import { EnemyType, type EnemyDef } from '../types';

// Damage tuned so bats kill player in ~6 hits (100hp / 6 ≈ 16)
// Later enemies hit proportionally harder
// unlockAt is fraction of total game duration (0–1)
export const ENEMY_DEFS: EnemyDef[] = [
  {
    type: EnemyType.Bat,
    name: 'Bat',
    color: 0x8b4513,
    size: 10,
    baseHp: 8,
    baseDamage: 16,
    baseSpeed: 100,
    xpValue: 1,
    unlockAt: 0,
    behavior: 'chase',
  },
  {
    type: EnemyType.Skeleton,
    name: 'Skeleton',
    color: 0xd2b48c,
    size: 12,
    baseHp: 25,
    baseDamage: 18,
    baseSpeed: 60,
    xpValue: 2,
    unlockAt: 0.03,
    behavior: 'chase',
  },
  {
    type: EnemyType.Zombie,
    name: 'Zombie',
    color: 0x6b3f2f,
    size: 14,
    baseHp: 50,
    baseDamage: 20,
    baseSpeed: 40,
    xpValue: 3,
    unlockAt: 0.10,
    behavior: 'swarm',
  },
  {
    type: EnemyType.Ghost,
    name: 'Ghost',
    color: 0xc0c0ff,
    size: 12,
    baseHp: 15,
    baseDamage: 14,
    baseSpeed: 90,
    xpValue: 3,
    unlockAt: 0.17,
    behavior: 'cross',
  },
  {
    type: EnemyType.Werewolf,
    name: 'Werewolf',
    color: 0x808080,
    size: 16,
    baseHp: 80,
    baseDamage: 24,
    baseSpeed: 120,
    xpValue: 5,
    unlockAt: 0.27,
    behavior: 'chase',
  },
  {
    type: EnemyType.Mummy,
    name: 'Mummy',
    color: 0xf5deb3,
    size: 14,
    baseHp: 120,
    baseDamage: 22,
    baseSpeed: 35,
    xpValue: 5,
    unlockAt: 0.37,
    behavior: 'swarm',
  },
  {
    type: EnemyType.Vampire,
    name: 'Vampire',
    color: 0x8b0000,
    size: 14,
    baseHp: 100,
    baseDamage: 28,
    baseSpeed: 110,
    xpValue: 8,
    unlockAt: 0.50,
    behavior: 'teleport',
  },
  {
    type: EnemyType.Lich,
    name: 'Lich',
    color: 0x4b0082,
    size: 16,
    baseHp: 200,
    baseDamage: 32,
    baseSpeed: 50,
    xpValue: 12,
    unlockAt: 0.67,
    behavior: 'orbit',
  },
  {
    type: EnemyType.Dragon,
    name: 'Dragon',
    color: 0xff4500,
    size: 24,
    baseHp: 500,
    baseDamage: 40,
    baseSpeed: 70,
    xpValue: 20,
    unlockAt: 0.83,
    behavior: 'chase',
  },
  {
    type: EnemyType.Reaper,
    name: 'Reaper',
    color: 0x1a1a2e,
    size: 18,
    baseHp: 800,
    baseDamage: 56,
    baseSpeed: 80,
    xpValue: 50,
    unlockAt: 0.93,
    behavior: 'teleport',
  },
  {
    type: EnemyType.Death,
    name: 'Death',
    color: 0x6622aa,
    size: 14,
    baseHp: 1,        // overridden at spawn
    baseDamage: 100,
    baseSpeed: 120,     // overridden at runtime to 80% of player speed
    xpValue: 500,
    unlockAt: 1.0,     // never via normal spawner
    behavior: 'chase',
  },
];
