import { WeaponType, type WeaponDef } from '../types';

export const WEAPON_DEFS: WeaponDef[] = [
  // ─── Melee (swing around player) ───
  {
    type: WeaponType.Whip,
    name: 'Whip',
    category: 'melee',
    description: 'Strikes in a wide area in front of you',
    color: 0xc0a060,
    baseDamage: 10,
    baseCooldown: 1200,
    baseArea: 80,
    baseDuration: 200,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.1, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.Sword,
    name: 'Sword',
    category: 'melee',
    description: 'Slashes in a wide arc around you',
    color: 0xc0c0c0,
    baseDamage: 15,
    baseCooldown: 1500,
    baseArea: 60,
    baseDuration: 300,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.55, cooldown: 0.04, area: 0.12, amount: 1, pierce: 0, duration: 0.08 },
  },
  {
    type: WeaponType.Axe,
    name: 'Axe',
    category: 'melee',
    description: 'Heavy hit with high damage, slow speed',
    color: 0x808080,
    baseDamage: 25,
    baseCooldown: 2000,
    baseArea: 50,
    baseDuration: 250,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.65, cooldown: 0.04, area: 0.08, amount: 1, pierce: 0, duration: 0.05 },
  },
  {
    type: WeaponType.Knife,
    name: 'Knife',
    category: 'melee',
    description: 'Rapid strikes with a small but fast blade',
    color: 0xe0e0e0,
    baseDamage: 6,
    baseCooldown: 600,
    baseArea: 40,
    baseDuration: 150,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0.06, area: 0.05, amount: 1, pierce: 1, duration: 0.05 },
  },
  {
    type: WeaponType.Cross,
    name: 'Cross',
    category: 'melee',
    description: 'Lingering holy strike that hits enemies in front of you',
    color: 0xffd700,
    baseDamage: 12,
    baseCooldown: 1800,
    baseArea: 45,
    baseDuration: 600,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.1, amount: 1, pierce: 1, duration: 0.1 },
  },

  // ─── AoE (area damage) ───
  {
    type: WeaponType.Garlic,
    name: 'Garlic',
    category: 'aoe',
    description: 'Repulsive burst that pushes enemies away from the area',
    color: 0x90ee90,
    baseDamage: 3,
    baseCooldown: 500,
    baseArea: 60,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0.05, area: 0.15, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.HolyWater,
    name: 'Holy Water',
    category: 'aoe',
    description: 'Drops a damaging pool on the ground',
    color: 0x00bfff,
    baseDamage: 8,
    baseCooldown: 3000,
    baseArea: 50,
    baseDuration: 2000,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.12, amount: 1, pierce: 0, duration: 0.15 },
  },
  {
    type: WeaponType.FireWand,
    name: 'Fire Wand',
    category: 'aoe',
    description: 'Creates a fire explosion at random nearby position',
    color: 0xff6600,
    baseDamage: 20,
    baseCooldown: 2500,
    baseArea: 55,
    baseDuration: 300,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.55, cooldown: 0.05, area: 0.1, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.Lightning,
    name: 'Lightning',
    category: 'aoe',
    description: 'Chain lightning that arcs between enemies, extra hop per level',
    color: 0xffff00,
    baseDamage: 18,
    baseCooldown: 2000,
    baseArea: 40,
    baseDuration: 200,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 3,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.08, amount: 1, pierce: 1, duration: 0.05 },
  },
  {
    type: WeaponType.Meteor,
    name: 'Meteor',
    category: 'aoe',
    description: 'Calls down a massive meteor at a random location',
    color: 0xff3300,
    baseDamage: 40,
    baseCooldown: 5000,
    baseArea: 80,
    baseDuration: 500,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.65, cooldown: 0.04, area: 0.15, amount: 1, pierce: 0, duration: 0.1 },
  },

  // ─── Force Field (orbits/surrounds player) ───
  {
    type: WeaponType.HolyShield,
    name: 'Holy Shield',
    category: 'forcefield',
    description: 'Rotating shields orbit the player',
    color: 0xffffff,
    baseDamage: 8,
    baseCooldown: 0,
    baseArea: 80,
    baseDuration: 0,
    baseSpeed: 2,
    baseAmount: 2,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0, area: 0.1, amount: 1, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.FrostAura,
    name: 'Frost Aura',
    category: 'forcefield',
    description: 'Aura that progressively freezes nearby enemies the longer they stay',
    color: 0x87ceeb,
    baseDamage: 4,
    baseCooldown: 0,
    baseArea: 70,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.4, cooldown: 0, area: 0.15, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.PoisonCloud,
    name: 'Poison Cloud',
    category: 'forcefield',
    description: 'Toxic cloud that damages enemies over time',
    color: 0x00ff00,
    baseDamage: 2,
    baseCooldown: 0,
    baseArea: 90,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0, area: 0.12, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.ThunderRing,
    name: 'Thunder Ring',
    category: 'forcefield',
    description: 'Electric field that continuously zaps nearby enemies',
    color: 0xffcc00,
    baseDamage: 10,
    baseCooldown: 0,
    baseArea: 100,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0, area: 0.1, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.VoidField,
    name: 'Void Field',
    category: 'forcefield',
    description: 'Dark energy field that slows nearby enemies',
    color: 0x6600cc,
    baseDamage: 0,
    baseCooldown: 0,
    baseArea: 120,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0, cooldown: 0, area: 0.1, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.VoidBurn,
    name: 'Void Burn',
    category: 'forcefield',
    description: 'Dark energy field that damages nearby enemies',
    color: 0x9900ff,
    baseDamage: 6,
    baseCooldown: 0,
    baseArea: 60,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0, area: 0.1, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.Vortex,
    name: 'Vortex',
    category: 'forcefield',
    description: 'Pulls enemies in and tears them apart',
    color: 0xcc00ff,
    baseDamage: 12,
    baseCooldown: 0,
    baseArea: 60,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0, area: 0.1, amount: 0, pierce: 0, duration: 0 },
  },

  // ─── Projectile (fires in direction) ───
  {
    type: WeaponType.MagicMissile,
    name: 'Magic Missile',
    category: 'projectile',
    description: 'Fires a missile that targets the nearest enemy',
    color: 0xcc66ff,
    baseDamage: 10,
    baseCooldown: 1200,
    baseArea: 8,
    baseDuration: 2000,
    baseSpeed: 300,
    baseAmount: 1,
    basePierce: 1,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.05, amount: 1, pierce: 1, duration: 0.1 },
  },
  {
    type: WeaponType.Fireball,
    name: 'Fireball',
    category: 'projectile',
    description: 'Launches a slow fireball that burns through enemies',
    color: 0xff4400,
    baseDamage: 25,
    baseCooldown: 2500,
    baseArea: 12,
    baseDuration: 3000,
    baseSpeed: 180,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.55, cooldown: 0.05, area: 0.15, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.IceShard,
    name: 'Ice Shard',
    category: 'projectile',
    description: 'Fires fast ice shards that pierce enemies',
    color: 0x00ccff,
    baseDamage: 7,
    baseCooldown: 800,
    baseArea: 6,
    baseDuration: 1500,
    baseSpeed: 400,
    baseAmount: 2,
    basePierce: 3,
    levelScaling: { damage: 0.45, cooldown: 0.06, area: 0.05, amount: 1, pierce: 1, duration: 0.08 },
  },
  {
    type: WeaponType.Boomerang,
    name: 'Boomerang',
    category: 'projectile',
    description: 'Thrown boomerang that returns to the player',
    color: 0xcc9933,
    baseDamage: 12,
    baseCooldown: 1800,
    baseArea: 10,
    baseDuration: 2500,
    baseSpeed: 250,
    baseAmount: 1,
    basePierce: 5,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.08, amount: 1, pierce: 1, duration: 0.1 },
  },
  {
    type: WeaponType.Scythe,
    name: 'Scythe',
    category: 'projectile',
    description: 'Spiraling scythes that orbit outward',
    color: 0x666666,
    baseDamage: 15,
    baseCooldown: 2000,
    baseArea: 10,
    baseDuration: 3000,
    baseSpeed: 100,
    baseAmount: 1,
    basePierce: 8,
    levelScaling: { damage: 0.5, cooldown: 0.04, area: 0.1, amount: 1, pierce: 1, duration: 0.12 },
  },

  // ─── New Melee ───
  {
    type: WeaponType.Spear,
    name: 'Spear',
    category: 'melee',
    description: 'Long-range thrust that hits enemies at a distance',
    color: 0xbb8844,
    baseDamage: 8,
    baseCooldown: 800,
    baseArea: 100,
    baseDuration: 150,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0.06, area: 0.12, amount: 1, pierce: 0, duration: 0.05 },
  },
  {
    type: WeaponType.Mace,
    name: 'Mace',
    category: 'melee',
    description: 'Devastating overhead smash with massive impact',
    color: 0x886688,
    baseDamage: 35,
    baseCooldown: 2800,
    baseArea: 70,
    baseDuration: 350,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.7, cooldown: 0.04, area: 0.1, amount: 1, pierce: 0, duration: 0.08 },
  },

  // ─── New AoE ───
  {
    type: WeaponType.Quake,
    name: 'Quake',
    category: 'aoe',
    description: 'Ground slam centered on you, damages all nearby',
    color: 0x996633,
    baseDamage: 28,
    baseCooldown: 4000,
    baseArea: 100,
    baseDuration: 600,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.6, cooldown: 0.05, area: 0.15, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.SpiritBomb,
    name: 'Spirit Bomb',
    category: 'aoe',
    description: 'Charges a massive explosion at a random location',
    color: 0xdd88ff,
    baseDamage: 55,
    baseCooldown: 6000,
    baseArea: 120,
    baseDuration: 800,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.65, cooldown: 0.04, area: 0.15, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.PlagueCloud,
    name: 'Plague Cloud',
    category: 'aoe',
    description: 'Toxic cloud that poisons enemies — damage lingers after they leave',
    color: 0x88aa22,
    baseDamage: 2,
    baseCooldown: 4000,
    baseArea: 45,
    baseDuration: 2500,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.7, cooldown: 0.05, area: 0.15, amount: 1, pierce: 0, duration: 0.25 },
  },

  // ─── New Projectile ───
  {
    type: WeaponType.Shuriken,
    name: 'Shuriken',
    category: 'projectile',
    description: 'Hurls blades in all directions at once',
    color: 0xaaaaaa,
    baseDamage: 5,
    baseCooldown: 1000,
    baseArea: 6,
    baseDuration: 1200,
    baseSpeed: 350,
    baseAmount: 4,
    basePierce: 1,
    levelScaling: { damage: 0.4, cooldown: 0.06, area: 0.05, amount: 1, pierce: 1, duration: 0.08 },
  },
  {
    type: WeaponType.DeathRay,
    name: 'Death Ray',
    category: 'projectile',
    description: 'Piercing beam that rips through entire crowds',
    color: 0xff0044,
    baseDamage: 14,
    baseCooldown: 1800,
    baseArea: 8,
    baseDuration: 2500,
    baseSpeed: 380,
    baseAmount: 1,
    basePierce: 12,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.05, amount: 1, pierce: 2, duration: 0.1 },
  },
  {
    type: WeaponType.BoneToss,
    name: 'Bone Toss',
    category: 'projectile',
    description: 'Scatters bones in random directions',
    color: 0xddcc99,
    baseDamage: 9,
    baseCooldown: 1400,
    baseArea: 8,
    baseDuration: 2000,
    baseSpeed: 260,
    baseAmount: 3,
    basePierce: 2,
    levelScaling: { damage: 0.45, cooldown: 0.05, area: 0.08, amount: 1, pierce: 1, duration: 0.1 },
  },

  // ─── New Force Field ───
  {
    type: WeaponType.BloodAura,
    name: 'Blood Aura',
    category: 'forcefield',
    description: 'Drains nearby enemies, healing you with each pulse',
    color: 0xcc0033,
    baseDamage: 5,
    baseCooldown: 0,
    baseArea: 55,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0, area: 0.12, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.GravityWell,
    name: 'Gravity Well',
    category: 'forcefield',
    description: 'Warps space around you, pulling and slowing enemies',
    color: 0x3344aa,
    baseDamage: 3,
    baseCooldown: 0,
    baseArea: 110,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.4, cooldown: 0, area: 0.12, amount: 0, pierce: 0, duration: 0 },
  },
];
