import { EffectType, type EffectDef } from '../types';

export const EFFECT_DEFS: EffectDef[] = [
  {
    type: EffectType.XPBoost,
    name: 'XP Boost',
    description: 'Increases XP gained',
    color: 0x00ff88,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Speed,
    name: 'Speed Boost',
    description: 'Increases movement speed',
    color: 0x00ccff,
    maxLevel: 5,
    levelValues: [0.10, 0.18, 0.25, 0.32, 0.40],
  },
  {
    type: EffectType.Regen,
    name: 'Regeneration',
    description: 'Recover HP over time',
    color: 0xff6688,
    maxLevel: 5,
    levelValues: [0.5, 1.0, 1.5, 2.5, 4.0],
  },
  {
    type: EffectType.Shield,
    name: 'Shield',
    description: 'Block damage periodically',
    color: 0xccccff,
    maxLevel: 5,
    levelValues: [1, 2, 3, 4, 6],
  },
  {
    type: EffectType.Magnet,
    name: 'Magnet',
    description: 'Increases XP pickup range',
    color: 0xff00ff,
    maxLevel: 5,
    levelValues: [0.30, 0.55, 0.80, 1.05, 1.40],
  },
  {
    type: EffectType.Cooldown,
    name: 'Cooldown Reduction',
    description: 'Reduces weapon cooldowns',
    color: 0x6666ff,
    maxLevel: 5,
    levelValues: [0.08, 0.14, 0.20, 0.26, 0.32],
  },
  {
    type: EffectType.Might,
    name: 'Might',
    description: 'Increases all damage dealt',
    color: 0xff3333,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Armor,
    name: 'Armor',
    description: 'Reduces damage taken',
    color: 0x999999,
    maxLevel: 5,
    levelValues: [3, 5, 8, 11, 15],
  },
  {
    type: EffectType.Luck,
    name: 'Luck',
    description: 'Better level-up choices and drop rates',
    color: 0xffcc00,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Revival,
    name: 'Revival',
    description: 'Revive once on death with partial HP',
    color: 0xff88ff,
    maxLevel: 5,
    levelValues: [0.20, 0.35, 0.50, 0.75, 1.0],
  },
  {
    type: EffectType.StrongAuras,
    name: 'Strong Auras',
    description: 'Increases AoE and force field size',
    color: 0x8844ff,
    maxLevel: 5,
    levelValues: [0.15, 0.30, 0.45, 0.60, 0.80],
  },
  {
    type: EffectType.Fury,
    name: 'Fury',
    description: 'Increases melee attack rate',
    color: 0xff4400,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Focused,
    name: 'Focused',
    description: 'More and faster projectiles',
    color: 0x00ffcc,
    maxLevel: 5,
    levelValues: [1, 2, 3, 4, 5],
  },
  {
    type: EffectType.Evolution,
    name: 'Evolution',
    description: 'Map evolves faster, reshaping the world',
    color: 0x44bb44,
    maxLevel: 5,
    levelValues: [0.5, 1.25, 2.0, 4.0, 8.0],
  },
  {
    type: EffectType.Thorns,
    name: 'Thorns',
    description: 'Reflect damage back to enemies on contact',
    color: 0x66aa44,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.50, 0.70],
  },
  {
    type: EffectType.Lifesteal,
    name: 'Lifesteal',
    description: 'Heal a portion of weapon damage dealt',
    color: 0xcc2244,
    maxLevel: 5,
    levelValues: [0.03, 0.05, 0.08, 0.12, 0.18],
  },
  {
    type: EffectType.Berserk,
    name: 'Berserk',
    description: 'Deal bonus damage when below half HP',
    color: 0xff2200,
    maxLevel: 5,
    levelValues: [0.20, 0.35, 0.50, 0.70, 1.0],
  },
  {
    type: EffectType.Dodge,
    name: 'Dodge',
    description: 'Chance to completely avoid incoming damage',
    color: 0x44dddd,
    maxLevel: 5,
    levelValues: [0.05, 0.10, 0.15, 0.20, 0.28],
  },
  {
    type: EffectType.CritChance,
    name: 'Crit Chance',
    description: 'Increases critical hit rate for all weapons',
    color: 0xff6600,
    maxLevel: 5,
    levelValues: [0.08, 0.14, 0.20, 0.28, 0.38],
  },
  {
    type: EffectType.Knockback,
    name: 'Knockback',
    description: 'Weapon hits push enemies away from you',
    color: 0x88bbdd,
    maxLevel: 5,
    levelValues: [10, 25, 50, 80, 120],
  },
  {
    type: EffectType.SlowAura,
    name: 'Slow Aura',
    description: 'Nearby enemies move slower at all times',
    color: 0x6688cc,
    maxLevel: 5,
    levelValues: [0.10, 0.18, 0.25, 0.32, 0.40],
  },
  {
    type: EffectType.GoldFind,
    name: 'Gold Find',
    description: 'Enemies drop more gold on kill',
    color: 0xeecc44,
    maxLevel: 5,
    levelValues: [1, 1, 2, 2, 3],
  },
  {
    type: EffectType.Duration,
    name: 'Duration',
    description: 'Weapon effects and projectiles last longer',
    color: 0xaa88cc,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.50, 0.70],
  },
  {
    type: EffectType.Growth,
    name: 'Growth',
    description: 'Maximum HP slowly increases over time',
    color: 0x44cc88,
    maxLevel: 5,
    levelValues: [0.5, 1.0, 1.5, 2.5, 4.0],
  },
  {
    type: EffectType.Vitality,
    name: 'Vitality',
    description: 'Raises maximum HP up to 250%',
    color: 0xff4488,
    maxLevel: 5,
    levelValues: [0.20, 0.40, 0.70, 1.05, 1.50],
  },
  {
    type: EffectType.Housekeeping,
    name: 'Housekeeping',
    description: 'Chance to clear enemies when the map evolves',
    color: 0x88ccaa,
    maxLevel: 5,
    levelValues: [0.10, 0.25, 0.40, 0.60, 0.80],
  },
];
