import { EffectType, type EffectDef } from '../types';

// All effects capped at 3 levels
export const EFFECT_DEFS: EffectDef[] = [
  {
    type: EffectType.XPBoost,
    name: 'XP Boost',
    description: 'Increases XP gained',
    color: 0x00ff88,
    maxLevel: 3,
    levelValues: [0.15, 0.30, 0.50],
  },
  {
    type: EffectType.Speed,
    name: 'Speed Boost',
    description: 'Increases movement speed',
    color: 0x00ccff,
    maxLevel: 3,
    levelValues: [0.10, 0.20, 0.35],
  },
  {
    type: EffectType.Regen,
    name: 'Regeneration',
    description: 'Recover HP over time',
    color: 0xff6688,
    maxLevel: 3,
    levelValues: [0.5, 1.5, 3],
  },
  {
    type: EffectType.Shield,
    name: 'Shield',
    description: 'Block damage periodically',
    color: 0xccccff,
    maxLevel: 3,
    levelValues: [1, 2, 4],
  },
  {
    type: EffectType.Magnet,
    name: 'Magnet',
    description: 'Increases XP pickup range',
    color: 0xff00ff,
    maxLevel: 3,
    levelValues: [0.30, 0.70, 1.20],
  },
  {
    type: EffectType.Cooldown,
    name: 'Cooldown Reduction',
    description: 'Reduces weapon cooldowns',
    color: 0x6666ff,
    maxLevel: 3,
    levelValues: [0.08, 0.16, 0.25],
  },
  {
    type: EffectType.Might,
    name: 'Might',
    description: 'Increases all damage dealt',
    color: 0xff3333,
    maxLevel: 3,
    levelValues: [0.15, 0.30, 0.50],
  },
  {
    type: EffectType.Armor,
    name: 'Armor',
    description: 'Reduces damage taken',
    color: 0x999999,
    maxLevel: 3,
    levelValues: [3, 6, 10],
  },
  {
    type: EffectType.Luck,
    name: 'Luck',
    description: 'Better level-up choices and drop rates',
    color: 0xffcc00,
    maxLevel: 3,
    levelValues: [0.15, 0.30, 0.50],
  },
  {
    type: EffectType.Revival,
    name: 'Revival',
    description: 'Revive once on death with partial HP',
    color: 0xff88ff,
    maxLevel: 3,
    levelValues: [0.25, 0.50, 1.0],
  },
];
