import { EffectType, type EffectDef } from '../types';

export const EFFECT_DEFS: EffectDef[] = [
  {
    type: EffectType.XPBoost,
    name: 'XP Boost',
    description: 'Increases XP gained',
    color: 0x00ff88,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Speed,
    name: 'Speed Boost',
    description: 'Increases movement speed',
    color: 0x00ccff,
    maxLevel: 5,
    levelValues: [0.10, 0.18, 0.25, 0.32, 0.40],
  },
  {
    type: EffectType.Regen,
    name: 'Regeneration',
    description: 'Recover HP over time',
    color: 0xff6688,
    maxLevel: 5,
    levelValues: [0.5, 1.0, 1.5, 2.5, 4.0],
  },
  {
    type: EffectType.Shield,
    name: 'Shield',
    description: 'Block damage periodically',
    color: 0xccccff,
    maxLevel: 5,
    levelValues: [1, 2, 3, 4, 6],
  },
  {
    type: EffectType.Magnet,
    name: 'Magnet',
    description: 'Increases XP pickup range',
    color: 0xff00ff,
    maxLevel: 5,
    levelValues: [0.30, 0.55, 0.80, 1.05, 1.40],
  },
  {
    type: EffectType.Cooldown,
    name: 'Cooldown Reduction',
    description: 'Reduces weapon cooldowns',
    color: 0x6666ff,
    maxLevel: 5,
    levelValues: [0.08, 0.14, 0.20, 0.26, 0.32],
  },
  {
    type: EffectType.Might,
    name: 'Might',
    description: 'Increases all damage dealt',
    color: 0xff3333,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Armor,
    name: 'Armor',
    description: 'Reduces damage taken',
    color: 0x999999,
    maxLevel: 5,
    levelValues: [3, 5, 8, 11, 15],
  },
  {
    type: EffectType.Luck,
    name: 'Luck',
    description: 'Better level-up choices and drop rates',
    color: 0xffcc00,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Revival,
    name: 'Revival',
    description: 'Revive once on death with partial HP',
    color: 0xff88ff,
    maxLevel: 5,
    levelValues: [0.20, 0.35, 0.50, 0.75, 1.0],
  },
  {
    type: EffectType.StrongAuras,
    name: 'Strong Auras',
    description: 'Increases AoE and force field size',
    color: 0x8844ff,
    maxLevel: 5,
    levelValues: [0.15, 0.30, 0.45, 0.60, 0.80],
  },
  {
    type: EffectType.Fury,
    name: 'Fury',
    description: 'Increases melee attack rate',
    color: 0xff4400,
    maxLevel: 5,
    levelValues: [0.15, 0.25, 0.35, 0.45, 0.55],
  },
  {
    type: EffectType.Focused,
    name: 'Focused',
    description: 'More and faster projectiles',
    color: 0x00ffcc,
    maxLevel: 5,
    levelValues: [1, 2, 3, 4, 5],
  },
];
