import { WeaponType, type WeaponDef } from '../types';

export const WEAPON_DEFS: WeaponDef[] = [
  // ─── Melee (swing around player) ───
  {
    type: WeaponType.Whip,
    name: 'Whip',
    category: 'melee',
    description: 'Strikes horizontally in front of you',
    color: 0xc0a060,
    baseDamage: 10,
    baseCooldown: 1200,
    baseArea: 80,
    baseDuration: 200,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.1, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.Sword,
    name: 'Sword',
    category: 'melee',
    description: 'Slashes in a wide arc around you',
    color: 0xc0c0c0,
    baseDamage: 15,
    baseCooldown: 1500,
    baseArea: 60,
    baseDuration: 300,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.55, cooldown: 0.04, area: 0.12, amount: 1, pierce: 0, duration: 0.08 },
  },
  {
    type: WeaponType.Axe,
    name: 'Axe',
    category: 'melee',
    description: 'Heavy hit with high damage, slow speed',
    color: 0x808080,
    baseDamage: 25,
    baseCooldown: 2000,
    baseArea: 50,
    baseDuration: 250,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.65, cooldown: 0.04, area: 0.08, amount: 1, pierce: 0, duration: 0.05 },
  },
  {
    type: WeaponType.Knife,
    name: 'Knife',
    category: 'melee',
    description: 'Fast stabs in front of you',
    color: 0xe0e0e0,
    baseDamage: 6,
    baseCooldown: 600,
    baseArea: 40,
    baseDuration: 150,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 2,
    levelScaling: { damage: 0.45, cooldown: 0.06, area: 0.05, amount: 1, pierce: 1, duration: 0.05 },
  },
  {
    type: WeaponType.Cross,
    name: 'Cross',
    category: 'melee',
    description: 'Spinning cross that returns like a boomerang',
    color: 0xffd700,
    baseDamage: 12,
    baseCooldown: 1800,
    baseArea: 45,
    baseDuration: 600,
    baseSpeed: 200,
    baseAmount: 1,
    basePierce: 5,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.1, amount: 1, pierce: 1, duration: 0.1 },
  },

  // ─── AoE (area damage) ───
  {
    type: WeaponType.Garlic,
    name: 'Garlic',
    category: 'aoe',
    description: 'Damages nearby enemies and reduces their speed',
    color: 0x90ee90,
    baseDamage: 3,
    baseCooldown: 500,
    baseArea: 60,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0.05, area: 0.15, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.HolyWater,
    name: 'Holy Water',
    category: 'aoe',
    description: 'Drops a damaging pool on the ground',
    color: 0x00bfff,
    baseDamage: 8,
    baseCooldown: 3000,
    baseArea: 50,
    baseDuration: 2000,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.12, amount: 1, pierce: 0, duration: 0.15 },
  },
  {
    type: WeaponType.FireWand,
    name: 'Fire Wand',
    category: 'aoe',
    description: 'Creates a fire explosion at random nearby position',
    color: 0xff6600,
    baseDamage: 20,
    baseCooldown: 2500,
    baseArea: 55,
    baseDuration: 300,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.55, cooldown: 0.05, area: 0.1, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.Lightning,
    name: 'Lightning',
    category: 'aoe',
    description: 'Strikes the nearest enemy with chain lightning',
    color: 0xffff00,
    baseDamage: 18,
    baseCooldown: 2000,
    baseArea: 40,
    baseDuration: 200,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 3,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.08, amount: 1, pierce: 1, duration: 0.05 },
  },
  {
    type: WeaponType.Meteor,
    name: 'Meteor',
    category: 'aoe',
    description: 'Calls down a massive meteor at a random location',
    color: 0xff3300,
    baseDamage: 40,
    baseCooldown: 5000,
    baseArea: 80,
    baseDuration: 500,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.65, cooldown: 0.04, area: 0.15, amount: 1, pierce: 0, duration: 0.1 },
  },

  // ─── Force Field (orbits/surrounds player) ───
  {
    type: WeaponType.HolyShield,
    name: 'Holy Shield',
    category: 'forcefield',
    description: 'Rotating shields orbit the player',
    color: 0xffffff,
    baseDamage: 8,
    baseCooldown: 0,
    baseArea: 80,
    baseDuration: 0,
    baseSpeed: 2,
    baseAmount: 2,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0, area: 0.1, amount: 1, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.FrostAura,
    name: 'Frost Aura',
    category: 'forcefield',
    description: 'Freezing field that slows and damages nearby enemies',
    color: 0x87ceeb,
    baseDamage: 4,
    baseCooldown: 0,
    baseArea: 70,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.4, cooldown: 0, area: 0.15, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.PoisonCloud,
    name: 'Poison Cloud',
    category: 'forcefield',
    description: 'Toxic cloud that damages enemies over time',
    color: 0x00ff00,
    baseDamage: 2,
    baseCooldown: 0,
    baseArea: 90,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0, area: 0.12, amount: 0, pierce: 0, duration: 0 },
  },
  {
    type: WeaponType.ThunderRing,
    name: 'Thunder Ring',
    category: 'forcefield',
    description: 'Electric ring that periodically zaps nearby enemies',
    color: 0xffcc00,
    baseDamage: 10,
    baseCooldown: 1500,
    baseArea: 100,
    baseDuration: 200,
    baseSpeed: 3,
    baseAmount: 3,
    basePierce: 99,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.1, amount: 1, pierce: 0, duration: 0.05 },
  },
  {
    type: WeaponType.VoidField,
    name: 'Void Field',
    category: 'forcefield',
    description: 'Dark energy field that pulls in and damages enemies',
    color: 0x6600cc,
    baseDamage: 6,
    baseCooldown: 0,
    baseArea: 120,
    baseDuration: 0,
    baseSpeed: 0,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.45, cooldown: 0, area: 0.1, amount: 0, pierce: 0, duration: 0 },
  },

  // ─── Projectile (fires in direction) ───
  {
    type: WeaponType.MagicMissile,
    name: 'Magic Missile',
    category: 'projectile',
    description: 'Fires a homing missile at the nearest enemy',
    color: 0xcc66ff,
    baseDamage: 10,
    baseCooldown: 1200,
    baseArea: 8,
    baseDuration: 2000,
    baseSpeed: 300,
    baseAmount: 1,
    basePierce: 1,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.05, amount: 1, pierce: 1, duration: 0.1 },
  },
  {
    type: WeaponType.Fireball,
    name: 'Fireball',
    category: 'projectile',
    description: 'Launches a slow, explosive fireball',
    color: 0xff4400,
    baseDamage: 25,
    baseCooldown: 2500,
    baseArea: 12,
    baseDuration: 3000,
    baseSpeed: 180,
    baseAmount: 1,
    basePierce: 99,
    levelScaling: { damage: 0.55, cooldown: 0.05, area: 0.15, amount: 1, pierce: 0, duration: 0.1 },
  },
  {
    type: WeaponType.IceShard,
    name: 'Ice Shard',
    category: 'projectile',
    description: 'Fires fast ice shards that pierce enemies',
    color: 0x00ccff,
    baseDamage: 7,
    baseCooldown: 800,
    baseArea: 6,
    baseDuration: 1500,
    baseSpeed: 400,
    baseAmount: 2,
    basePierce: 3,
    levelScaling: { damage: 0.45, cooldown: 0.06, area: 0.05, amount: 1, pierce: 1, duration: 0.08 },
  },
  {
    type: WeaponType.Boomerang,
    name: 'Boomerang',
    category: 'projectile',
    description: 'Thrown boomerang that returns to the player',
    color: 0xcc9933,
    baseDamage: 12,
    baseCooldown: 1800,
    baseArea: 10,
    baseDuration: 2500,
    baseSpeed: 250,
    baseAmount: 1,
    basePierce: 5,
    levelScaling: { damage: 0.5, cooldown: 0.05, area: 0.08, amount: 1, pierce: 1, duration: 0.1 },
  },
  {
    type: WeaponType.Scythe,
    name: 'Scythe',
    category: 'projectile',
    description: 'Spiraling scythes that orbit outward',
    color: 0x666666,
    baseDamage: 15,
    baseCooldown: 2000,
    baseArea: 10,
    baseDuration: 3000,
    baseSpeed: 100,
    baseAmount: 1,
    basePierce: 8,
    levelScaling: { damage: 0.5, cooldown: 0.04, area: 0.1, amount: 1, pierce: 1, duration: 0.12 },
  },
];
